### ISSUE TITLE
Love the rando but...

### ISSUE THREAD

**Issue by Tkpandacookie** [Truthkey/Birth-by-Sleep-Randomizer#2]
So I have a couple things that just don't work properly
1. no matter if I choose "allow weak bosses" or "allow strong bosses" I just get them both anyway spawning in
2. As Aqua, I can't finish Olympus (I'm not sure if its just my game) but no matter what on the third fight it stays as a black screen and soft locks the game
3. If there is a way you could fix custom seeds? I was trying to run with a friend and no matter how many times we put in a seed the other made it would just keep it as "Randomization0"

Was also wondering on the side if you were planning on adding anything like the KH2 rando does? Like random keyblade stats, being able to choose what bosses get randomized and whatnot? 

all this being said, this is my favorite KH game and I love that you put in work for a rando of it :) been waiting a long time for one

**Comment by Sirius902** [comment]
As for problem 3 it seems that only pressing the `Random Seed` button will change the seed, typing into the `Randomization Seed` text box does and / or incrementing the number through the up and down arrows does not actually change anything.

**Comment by Truthkey** [comment]
I have fixed the seed issue not updating the actual seed used. Some of your issues should also be alleviated in the latest update.
